dataset:
  names: SeizeIT2-ECG-TimeVQVAE-AD
  root_dir: /home/swolf/asim_shared/preprocessed_data
  downsample_freq: 8
  stride: -1
  in_channels: 1
  batch_sizes:
    stage1: 256 #512
    stage2: 512 #256 #512
  num_workers: 0
  heartbeats_per_minute: 75 # Need to find a way of calculating the true bpm look into set_window_size() for contexts
  n_periods: 400  # window_size = n_periods * period_length; REF: MERLIN++; How many hearth beats we want approximately in one sample
  expand_labels: True # If True, labels are expanded to windows from pre 5 to post 3 seconds

exp_params:
  lr:
    stage1: 0.001
    stage2: 0.001
  linear_warmup_rate: 0.1

trainer_params:
  gpus:
    - 0
  max_steps:
    stage1: 10000
    stage2: 50000
  max_hours:
    stage1: 12
    stage2: 12
  val_check_interval:
    stage1: 1000
    stage2: 2000


encoder:
  dim: 128
  n_resnet_blocks: 6
  downsampled_width: 16

decoder:
  n_resnet_blocks: 6

VQ-VAE:
  n_fft: 8
  codebook_size: 256 #128


MaskGIT:
  choice_temperature: 2  # for masking
  T: 25
  mask_scheduling_func: "cosine"
  prior_model:
    hidden_dim: 256
    depth: 6
    heads: 8
    attn_dim_head: 32
    ff_mult: 4
    use_rmsnorm: True
    dropout: 0.2