dataset:
  names: SeizeIT2-ECG-TimeVQVAE-AD
  root_dir: /home/swolf/asim_shared/preprocessed_data
  downsample_freq: 8
  stride: -1
  in_channels: 1
  batch_sizes:
    stage1: 1792
    stage2: 576
  num_workers: 0
  heartbeats_per_minute: 75
  n_periods: 120
  expand_labels: False

exp_params:
  lr:
    stage1: 0.001
    stage2: 0.001
  linear_warmup_rate: 0.1

trainer_params:
  max_steps:
    stage1: 10000000000
    stage2: 10000000000
  max_hours:
    stage1: 48
    stage2: 48
  val_check_interval:
    stage1: 1000
    stage2: 1000

encoder:
  dim: 128
  n_resnet_blocks: 10
  downsampled_width: 16

decoder:
  n_resnet_blocks: 10

VQ-VAE:
  n_fft: 16
  codebook_size: 1024

MaskGIT:
  choice_temperature: 2
  T: 25
  mask_scheduling_func: "cosine"
  prior_model:
    hidden_dim: 384
    depth: 8
    heads: 6
    attn_dim_head: 32
    ff_mult: 4
    use_rmsnorm: True
    dropout: 0.2