# config_faithful-butterfly.yaml
dataset:
  names: SeizeIT2-ECG-TimeVQVAE-AD
  root_dir: /home/swolf/asim_shared/preprocessed_data
  downsample_freq: 8
  stride: -1
  in_channels: 1
  batch_sizes:
    stage1: 256
    stage2: 48
  num_workers: 0
  heartbeats_per_minute: 75
  n_periods: 120
  expand_labels: True

exp_params:
  lr:
    stage1: 0.001
    stage2: 0.001
  linear_warmup_rate: 0.1

trainer_params:
  max_steps:
    stage1: 15000
    stage2: 70000
  max_hours:
    stage1: 1
    stage2: 12
  val_check_interval:
    stage1: 1000
    stage2: 1000

encoder:
  dim: 128
  n_resnet_blocks: 10
  downsampled_width: 16

decoder:
  n_resnet_blocks: 10

VQ-VAE:
  n_fft: 16
  codebook_size: 1024

MaskGIT:
  choice_temperature: 2
  T: 25
  mask_scheduling_func: "cosine"
  prior_model:
    hidden_dim: 384
    depth: 12
    heads: 12
    attn_dim_head: 32
    ff_mult: 4
    use_rmsnorm: True
    dropout: 0.2